-- Supabase Schema for TonyBot Unified Platform («Точка переходу»)

-- 1. Таблиця користувачів
CREATE TABLE IF NOT EXISTS users (
    user_id TEXT PRIMARY KEY,
    username TEXT,
    first_name TEXT,
    last_name TEXT,
    phone TEXT,
    status TEXT DEFAULT 'free', -- free, base, support, vip
    current_day INT DEFAULT 1,
    avatar_url TEXT,
    utm_source TEXT,
    utm_medium TEXT,
    is_blocked BOOLEAN DEFAULT FALSE,
    join_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    last_active TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Таблиця тарифних пакетів
CREATE TABLE IF NOT EXISTS packages (
    id TEXT PRIMARY KEY, -- base, support, vip
    name TEXT NOT NULL,
    tag TEXT NOT NULL,
    price TEXT NOT NULL,
    old_price TEXT,
    desc_text TEXT,
    features JSONB,
    available_places INT
);

-- 3. Таблиця лідів (заявок на участь)
CREATE TABLE IF NOT EXISTS leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT REFERENCES users(user_id) ON DELETE CASCADE,
    package_name TEXT NOT NULL,
    status TEXT DEFAULT 'pending', -- pending, paid, cancelled
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Таблиця результатів тесту (7 питань)
CREATE TABLE IF NOT EXISTS test_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT REFERENCES users(user_id) ON DELETE CASCADE,
    score INT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Таблиця листування (історія чату користувача з ботом/ШІ/адміном)
CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT REFERENCES users(user_id) ON DELETE CASCADE,
    direction TEXT NOT NULL, -- user, bot, admin, system
    text TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Журнал доставки занять курсу
CREATE TABLE IF NOT EXISTS course_progress_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT REFERENCES users(user_id) ON DELETE CASCADE,
    day_num INT NOT NULL,
    delivery_type TEXT DEFAULT 'auto', -- auto, manual
    status TEXT NOT NULL, -- sent, failed
    error_message TEXT,
    sent_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Дії користувача (аналітика дій)
CREATE TABLE IF NOT EXISTS user_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT REFERENCES users(user_id) ON DELETE CASCADE,
    action_type TEXT NOT NULL,
    target_element TEXT,
    metadata JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==============================================================================
-- SQL МІГРАЦІЯ (виконайте в Supabase SQL Editor, якщо таблиці вже були створені):
-- ==============================================================================
-- ALTER TABLE leads DROP CONSTRAINT IF EXISTS leads_user_id_fkey;
-- ALTER TABLE test_results DROP CONSTRAINT IF EXISTS test_results_user_id_fkey;
-- ALTER TABLE messages DROP CONSTRAINT IF EXISTS messages_user_id_fkey;
-- ALTER TABLE course_progress_logs DROP CONSTRAINT IF EXISTS course_progress_logs_user_id_fkey;
-- ALTER TABLE user_actions DROP CONSTRAINT IF EXISTS user_actions_user_id_fkey;

-- ALTER TABLE users ALTER COLUMN user_id TYPE TEXT;
-- ALTER TABLE leads ALTER COLUMN user_id TYPE TEXT;
-- ALTER TABLE test_results ALTER COLUMN user_id TYPE TEXT;
-- ALTER TABLE messages ALTER COLUMN user_id TYPE TEXT;
-- ALTER TABLE course_progress_logs ALTER COLUMN user_id TYPE TEXT;
-- ALTER TABLE user_actions ALTER COLUMN user_id TYPE TEXT;

-- ALTER TABLE leads ADD CONSTRAINT leads_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE;
-- ALTER TABLE test_results ADD CONSTRAINT test_results_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE;
-- ALTER TABLE messages ADD CONSTRAINT messages_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE;
-- ALTER TABLE course_progress_logs ADD CONSTRAINT course_progress_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE;
-- ALTER TABLE user_actions ADD CONSTRAINT user_actions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE;
-- ==============================================================================

-- Початкові дані тарифів
INSERT INTO packages (id, name, tag, price, old_price, desc_text, features, available_places)
VALUES 
  ('base', 'Самостійно', 'Базовий', '20€', '100€', 'Повне самостійне проходження у своєму темпі', '["8 відео-уроків", "8 аудіопрактик", "Робочий зошит", "Доступ назавжди", "3 бонуси"]', NULL),
  ('support', 'Зі спікером', 'Супровід', '125€', '200€', 'Живий контакт і підтримка від Антоніни', '["Все з базового", "Telegram-група з учасницями", "Голосові відповіді від Антоніни", "1 Zoom-сесія", "3 бонуси"]', 5),
  ('vip', 'Індивідуально', 'VIP Супровід', '400€', '600€', 'Максимальна трансформація тет-а-тет', '["Все з Супроводу", "4 особисті сесії Zoom", "Чат 24/7 зі спікером", "Індивідуальна карта практик", "3 бонуси"]', 2)
ON CONFLICT (id) DO NOTHING;


-- 8. Системні налаштування (розклад розсилок тощо)
CREATE TABLE IF NOT EXISTS bot_settings (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Початкові налаштування розкладу (за замовчуванням 17:00 Київ)
INSERT INTO bot_settings (key, value)
VALUES ('scheduler_config', '{"broadcastHour": 17, "broadcastMinute": 0, "targetAudience": "paid", "lastBroadcastDate": ""}'::jsonb)
ON CONFLICT (key) DO NOTHING;
